export const FETCH_TODOS_REQUEST = "FETCH_TODOS_REQUEST";
export const FETCH_TODOS = "FETCH_TODOS";
export const FETCH_TODO = "FETCH_TODO";
export const FETCH_TODOS_FAILURE = "FETCH_TODOS_FAILURE";
export const ADD_TODO = "ADD_TODO";
export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const DELETE_TODO = "DELETE_TODO";
